version: '3'

services:
  db:
    image: postgres
    container_name: my-postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynetwork

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mydjangoapp
    ports:
      - "8000:8000"
    networks:
      - mynetwork
    depends_on:
      - db

networks:
  mynetwork:
